# Step 1 : vpc created
---
- name: Create VPC for Jenkins
  amazon.aws.ec2_vpc_net:
    state: present
    region: "{{ aws_region }}"
    name: "vpc_{{ name }}"
    cidr_block: "{{ vpc_cidr }}"
    dns_hostnames: true
    dns_support: true
    multi_ok: false
    tenancy: default
    profile: "{{ aws_profile }}"
    tags:
      Name: "jenkins"
  register: jenkins_vpc
