---
- name: Stop Ec2 instance with tag filters
  ec2_instance_info:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "tag:app": "{{ tag_value }}"
  register: ec2_jenkins  

- name: Kill EC2 Instance
  ec2:
    instance_ids: "{{ ec2_jenkins.instances[0].instance_id }}"
    state: absent
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"  
    wait: yes

- name: disassociate an elastic IP with a device
  ec2_eip:
    device_id: '{{ item.instance_id }}'
    ip: '{{ item.public_ip_address }}'
    release_on_disassociation: no
    state: absent
  when: item.public_ip_address is defined
  with_items: "{{ ec2_jenkins.instances }}"      
